name 'learn_the_basics_rhel'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_the_basics_rhel'
long_description 'Installs/Configures learn_the_basics_rhel'
version '0.1.0'

depends 'snippet'
depends 'workstation'
