transport:
  username: Administrator
  password: Pass@word1

platforms:
  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2
    driver:
      gui: false
      boot_timeout: 1200
