# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
end

vagrantfiles = %w[Vagrantfile.centos-72-chefdk]
vagrantfiles.each do |vagrantfile|
  load File.join(File.expand_path('../../../../vagrant'), vagrantfile)
end
