# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

chef_version = "stable-12.12.15"

Vagrant.configure(2) do |config|

  config.vm.define "workstation" do |cs|
    cs.vm.box = 'bento/ubuntu-14.04'
    cs.vm.hostname = "workstation.test"

    cs.vm.provider "vmware_fusion" do |v|
      v.memory = 2048
    end

    cs.vm.provision "chef_solo" do |chef|
      chef.product = "chef"
      chef.channel = chef_version.split('-')[0]
      chef.version = chef_version.split('-')[1]
      chef.cookbooks_path = "vendored-cookbooks"
      chef.add_recipe "chefspec::default"
      chef.log_level = "warn"
      chef.json = {
        "snippets" => {
          "node_platform" => "windows"
        }
      }
    end
  end
end
