---
driver:
  name: vagrant
  boot_timeout: 1200
  gui: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
  connection_timeout: 10
  connection_retries: 100

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
