# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

chef_version = "stable-12.12.15"

Vagrant.configure(2) do |config|

  config.vm.define "workstation" do |cs|
    cs.vm.box = 'bento/ubuntu-14.04'
    cs.vm.hostname = "workstation.test"
    cs.vm.network "private_network", ip: "192.168.145.132"

    cs.vm.provider "vmware_fusion" do |v|
      v.memory = 4096
      # Enable nested virtualization.
      v.customize ["modifyvm", :id, "--hwvirtex", "on"]
      v.vmx["vhv.enable"] = "TRUE"
      v.cpus = 4
    end

    cs.vm.provision "chef_solo" do |chef|
      chef.product = "chef"
      chef.channel = chef_version.split('-')[0]
      chef.version = chef_version.split('-')[1]
      chef.cookbooks_path = "vendored-cookbooks"
      chef.add_recipe "workstation::default"
      chef.add_recipe "workstation::virtualbox"
      chef.add_recipe "workstation::vagrant"
      chef.add_recipe "local_development::default"
      chef.log_level = "warn"
      chef.json = {
        "scenarios" => [
          {
            "cookbook" => "learn_chef_httpd",
            "drivers" => ["vagrant", "ec2", "azure", "gcp"],
            "platform" => "rhel",
            "overlay_drivers" => ["ec2", "azure", "gcp"]
          },
          {
            "cookbook" => "learn_chef_apache2",
            "drivers" => ["vagrant", "ec2", "azure", "gcp"],
            "platform" => "ubuntu",
            "overlay_drivers" => ["ec2", "azure", "gcp"]
          },
          {
            "cookbook" => "learn_chef_iis",
            "drivers" => ["vagrant", "ec2", "azure", "gcp"],
            "platform" => "windows",
            "overlay_drivers" => ["vagrant", "ec2", "azure", "gcp"]
          }
        ],
        "driver_config" => {
          "learn_chef_httpd" => {
            "ec2" => {
              "aws_ssh_key_id" => "learn-chef",
              "aws_region" => "us-east-1",
              "aws_availability_zone" => "b",
              "aws_subnet" => "subnet-3f22bd15",
              "aws_ami" => "ami-6d1c2007",
              "aws_security_group_ids" => "sg-0e08cf75",
              "aws_ssh_key" => "/root/.ssh/learn-chef.pem"
            },
            "azure" => {
              "azure_subscription_id" => File.readlines('secrets/azure/credentials').grep(/^\[(.+)\]$/){ $1 }[0],
              "azure_ssh_key" => "/root/.ssh/learn-chef.pem"
            },
            "gcp" => {
              "gcp_ssh_key" => "/root/.ssh/learn-chef.pem"
            }
          },
          "learn_chef_apache2" => {
            "ec2" => {
              "aws_ssh_key_id" => "learn-chef",
              "aws_region" => "us-east-1",
              "aws_availability_zone" => "b",
              "aws_subnet" => "subnet-3f22bd15",
              "aws_ami" => "ami-49c9295f",
              "aws_security_group_ids" => "sg-0e08cf75",
              "aws_ssh_key" => "/root/.ssh/learn-chef.pem"
            },
            "azure" => {
              "azure_subscription_id" => File.readlines('secrets/azure/credentials').grep(/^\[(.+)\]$/){ $1 }[0],
              "azure_ssh_key" => "/root/.ssh/learn-chef.pem"
            },
            "gcp" => {
              "gcp_ssh_key" => "/root/.ssh/learn-chef.pem"
            }
          },
          "learn_chef_iis" => {
            "ec2" => {
              "aws_ssh_key_id" => "learn-chef",
              "aws_region" => "us-east-1",
              "aws_availability_zone" => "b",
              "aws_subnet" => "subnet-3f22bd15",
              "aws_ami" => "ami-abf616bd",
              "aws_security_group_ids" => "sg-48984132",
              "aws_ssh_key" => "/root/.ssh/learn-chef.pem"
            },
            "azure" => {
              "azure_subscription_id" => File.readlines('secrets/azure/credentials').grep(/^\[(.+)\]$/){ $1 }[0]
            },
            "gcp" => {
              "gcp_ssh_key" => "/root/.ssh/learn-chef.pem"
            }
          }
        }
      }
    end
  end
end
