name 'snippet'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures snippet'
long_description 'Installs/Configures snippet'
version '0.1.0'
