# -*- mode: ruby -*-
# vi: set ft=ruby :
chef_version = "stable-12.12.15"

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-14.04"

  config.vm.define "node1-centos" do |cs|
    cs.vm.box = "bento/centos-7.2"
    cs.vm.hostname = "node1-centos"
    #cs.vm.network "private_network", ip: "192.168.145.134"
    cs.vm.provision "shell", path: "../../shared/scripts/report_ip_address.sh"
  end

  config.vm.define "node1-ubuntu" do |cs|
    cs.vm.box = "boxcutter/ubuntu1404" #"bento/ubuntu-14.04"
    cs.vm.hostname = "node1-ubuntu"
    #cs.vm.network "private_network", ip: "192.168.145.135"
    cs.vm.provision "shell", path: "../../shared/scripts/report_ip_address.sh"
  end

  config.vm.define "node1-windows" do |cs|
    cs.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
    cs.vm.guest = :windows
    cs.vm.hostname = "node1-windows"
    #cs.vm.network "private_network", ip: "192.168.145.136"
    cs.winrm.username = "Administrator"
    cs.vm.provider "vmware_fusion" do |v|
      v.memory = 1024
      v.cpus = 1
      v.gui = false
    end
    cs.vm.provision "shell", path: "../../shared/scripts/ReportIPAddress.ps1"
  end

  config.vm.define "workstation-ubuntu" do |cs|
    cs.vm.box = "bento/ubuntu-14.04"
    cs.vm.hostname = "workstation-ubuntu"
    cs.vm.network "private_network", ip: "192.168.145.132"

    cs.vm.provider "vmware_fusion" do |v|
      v.memory = 1024
    end

    cs.vm.provision "chef_solo" do |chef|
      chef.product = "chef"
      chef.channel = chef_version.split('-')[0]
      chef.version = chef_version.split('-')[1]
      chef.cookbooks_path = "vendored-cookbooks"
      chef.add_recipe "manage_a_node::default"
      chef.log_level = "warn"
      chef.json = {
        "snippets" => {
          "virtualization" => "hosted"
        },
        "nodes" => [
          {
            "name" => "node1-centos",
            "platform" => "rhel",
            "ssh_user" => "vagrant",
            "identity_file" => "~/.ssh/private_key",
            "ip_address" => "192.168.145.134",
            "cookbook" => "learn_chef_httpd"
          },
          {
            "name" => "node1-ubuntu",
            "platform" => "ubuntu",
            "ssh_user" => "vagrant",
            "identity_file" => "~/.ssh/private_key",
            "ip_address" => "192.168.145.135",
            "cookbook" => "learn_chef_apache2"
          },
          {
            "name" => "node1-windows",
            "platform" => "windows",
            "winrm_user" => "vagrant",
            "password" => "vagrant",
            "ip_address" => "undefined",
            "cookbook" => "learn_chef_iis"
          }
        ]
      }
    end
  end
end
