# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

chef_version = "stable-12.12.15"

Vagrant.configure(2) do |config|

  config.vm.define "workstation" do |cs|
    cs.vm.box = 'bento/ubuntu-14.04'
    cs.vm.hostname = "workstation.test"
    cs.vm.network "private_network", ip: "192.168.145.132"

    cs.vm.provider "vmware_fusion" do |v|
      v.memory = 2048
      # Enable nested virtualization.
      v.customize ["modifyvm", :id, "--hwvirtex", "on"]
      v.vmx["vhv.enable"] = "TRUE"
    end

    cs.vm.provision "chef_solo" do |chef|
      chef.product = "chef"
      chef.channel = chef_version.split('-')[0]
      chef.version = chef_version.split('-')[1]
      chef.cookbooks_path = "vendored-cookbooks"
      chef.add_recipe "workstation::default"
      chef.add_recipe "workstation::virtualbox"
      chef.add_recipe "workstation::vagrant"
      chef.add_recipe "local_development::default"
      chef.log_level = "warn"
      chef.json = {
        "scenarios" => [
          {
            "cookbook" => "learn_chef_httpd",
            "drivers" => "vagrant",
            "platform" => "rhel"
          }
        ]
      }
    end
  end
end
