---
driver:
  name: gce
  project: cheftraining-petchel
  zone: us-east1-c
  email: tpetchel@chef.io
  tags:
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: thomaspetchel
  ssh_key: <%= @config['gcp_ssh_key'] %>

platforms:
  - name: ubuntu-14.04
    driver:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1404-lts

suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
