---
driver:
  name: ec2
  aws_ssh_key_id: <%= @config['aws_ssh_key_id'] %>
  region: <%= @config['aws_region'] %>
  availability_zone: <%= @config['aws_availability_zone'] %>
  subnet_id: <%= @config['aws_subnet'] %>
  instance_type: t2.micro
  image_id: <%= @config['aws_ami'] %>
  security_group_ids: <%= @config['aws_security_group_ids'] %>
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: <%= @config['aws_ssh_key'] %>

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
